name: sstenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - cmocean=2.0
  - dask=2021.7.2
  - jupyter=1.0.0
  - matplotlib=3.5.1
  - python=3.7.12
  - xarray=0.20.2
  - s3fs=2021.10.1


